<a href="https://colab.research.google.com/github/RahulDogra-92/Deep-Learning-using-Pytorch/blob/main/Pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Matrix multiplication

In [ ]:
import torch

#tensors
torch.tensor([[2,3,5],[1,2,9]])

tensor([[2, 3, 5],
        [1, 2, 9]])

In [ ]:
#random values

torch.rand(2,2)

tensor([[0.4050, 0.7526],
        [0.9439, 0.1085]])

In [ ]:
a = torch.rand((3,5))
print(a)
print(a.shape)

tensor([[0.7890, 0.8268, 0.0244, 0.3576, 0.3975],
        [0.6518, 0.5004, 0.8282, 0.2729, 0.8808],
        [0.8014, 0.2646, 0.3539, 0.4236, 0.4306]])
torch.Size([3, 5])


In [ ]:
a = torch.rand((3,3))
b = torch.rand((3,3))

print(a,b)
# np.dot 
# torch.matmul

torch.matmul(a,b)

tensor([[0.2934, 0.4897, 0.2707],
        [0.8932, 0.2776, 0.3912],
        [0.4261, 0.8214, 0.2598]]) tensor([[0.4544, 0.2113, 0.0475],
        [0.2527, 0.0488, 0.0016],
        [0.5375, 0.4463, 0.6198]])


tensor([[0.4026, 0.2067, 0.1825],
        [0.6863, 0.3768, 0.2853],
        [0.5408, 0.2461, 0.1826]])

In [ ]:
.85 * .86

0.731

In [ ]:
a * b

tensor([[0.1333, 0.1035, 0.0129],
        [0.2257, 0.0136, 0.0006],
        [0.2290, 0.3666, 0.1610]])

In [ ]:
torch.zeros(2,2)

tensor([[0., 0.],
        [0., 0.]])

In [ ]:
torch.ones(2,2)

tensor([[1., 1.],
        [1., 1.]])

In [ ]:
torch.eye(2)

tensor([[1., 0.],
        [0., 1.]])

In [ ]:
x = torch .rand((3,5))
print(x)

tensor([[0.0035, 0.2248, 0.7655, 0.0957, 0.8000],
        [0.0018, 0.9368, 0.8922, 0.6749, 0.4799],
        [0.1436, 0.3919, 0.0317, 0.7528, 0.3310]])


In [ ]:
torch.from_numpy(x.numpy())

tensor([[0.0035, 0.2248, 0.7655, 0.0957, 0.8000],
        [0.0018, 0.9368, 0.8922, 0.6749, 0.4799],
        [0.1436, 0.3919, 0.0317, 0.7528, 0.3310]])

In [ ]:
l = [1,2,3,4]
torch.tensor(l)

tensor([1, 2, 3, 4])

**Practise**

Import PyTorch main library.
Create the variable your_first_tensor and set it to a random torch tensor of size 3 by 3.
Calculate its shape (dimension sizes) and set it to variable tensor_size.
Print the values of your_first_tensor and tensor_size

In [ ]:
import torch

your_first_tensor = torch.tensor((3, 3))

tensor_size = your_first_tensor.shape

print(your_first_tensor)
print(tensor_size)


tensor([3, 3])
torch.Size([2])


Create a matrix of ones with shape 3 by 3, and put it on variable tensor_of_ones.
Create an identity matrix with shape 3 by 3, and put it on variable identity_tensor.
Do a matrix multiplication of tensor_of_ones with identity_tensor and print its value.
Do an element-wise multiplication of tensor_of_ones with identity_tensor and print its value.

In [ ]:

# Create a matrix of ones with shape 3 by 3
tensor_of_ones = torch.ones(3, 3)

# Create an identity matrix with shape 3 by 3
identity_tensor = torch.eye(3)

# Do a matrix multiplication of tensor_of_ones with identity_tensor
matrices_multiplied = torch.matmul(tensor_of_ones, identity_tensor)
print(matrices_multiplied)

# Do an element-wise multiplication of tensor_of_ones with identity_tensor
element_multiplication = tensor_of_ones * identity_tensor
print(element_multiplication)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])
tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])


Forward Pass

In [ ]:
import torch

a = torch.tensor([2])
b = torch.tensor([-4])
c = torch.tensor([-2])
d = torch.tensor([2])

e = a + b
f = c * d

g = e * f

print(e,f,g)

tensor([-2]) tensor([-4]) tensor([8])


Initialize random tensors x, y and z, each having shape (1000, 1000).
Multiply x with y, putting the result in tensor q.
Do an elementwise multiplication of tensor z with tensor q, putting the results in f

In [ ]:
# Initialize tensors x, y and z
x = torch.rand(1000, 1000)
y = torch.rand(1000, 1000)
z = torch.rand(1000, 1000)

# Multiply x with y
q = x * y

# Multiply elementwise z with q
f = z * q

mean_f = torch.mean(f)
print(mean_f)

tensor(0.1251)


BackProp by auto diff

In [ ]:
import torch

x = torch.tensor(-3.,requires_grad=True)
y = torch.tensor(-5.,requires_grad=True)
z = torch.tensor(2.,requires_grad=True)

q = x + y
f = q * z

f.backward()

print("gradient of z", str(z.grad))
print("gradient of y", str(y.grad))
print("gradient of x", str(x.grad))

gradient of z tensor(-8.)
gradient of y tensor(2.)
gradient of x tensor(2.)


Initialize tensors x, y and z to values 4, -3 and 5.
Put the sum of tensors x and y in q, put the product of q and z in f.
Calculate the derivatives of the computational graph.
Print the gradients of the x, y and z tensors.

In [ ]:
# Initialize x, y and z to values 4, -3 and 5
x = torch.tensor(4., requires_grad=True)
y = torch.tensor(-3., requires_grad=True)
z = torch.tensor(5., requires_grad=True)

# Set q to sum of x and y, set f to product of q with z
q = x + y
f = q * z

# Compute the derivatives
f.backward()

# Print the gradients
print("Gradient of x is: " + str(x.grad))
print("Gradient of y is: " + str(y.grad))
print("Gradient of z is: " + str(z.grad))

Gradient of x is: tensor(5.)
Gradient of y is: tensor(5.)
Gradient of z is: tensor(1.)


Multiply tensors x and y, put the product in tensor q.
Do an elementwise multiplication of tensors z with q.
Calculate the gradients.

In [ ]:
x = torch.randn(1000,1000,requires_grad=True)
y = torch.randn(1000,1000,requires_grad=True)
z = torch.randn(1000,1000,requires_grad=True)
# Multiply tensors x and y
q = torch.matmul(x,y)

# Elementwise multiply tensors z with q
f = z * q

mean_f = torch.mean(f)

# Calculate the gradients
mean_f.backward()

Intro to Neural Networks

In [ ]:
#Work of Hidden Layers is to get good features

import torch

input_layer = torch.rand(10)

w1 = torch.rand(10,20)
w2 = torch.rand(20,20)
w3 = torch.rand(20,4)

h1 = torch.matmul(input_layer , w1)
h2 = torch.matmul(h1,w2)

output_layer = torch.matmul(h2, w3)

print(output_layer)

tensor([294.4204, 224.1800, 295.8161, 245.0787])


Pytorch way

In [ ]:
import torch
import torch.nn as nn

class Net(nn.Module):
  def __init__(self):
    super(Net, self).__init__() #calling the super class constructor
    self.fc1 = nn.Linear(10,20)
    self.fc2 = nn.Linear(20,20)
    self.output = nn.Linear(20,4)

  def forward(self, X):
    x1 = self.fc1(X)
    x2 = self.fc2(x1)
    x3 = self.output(x2)
    return x3

input_layer = torch.rand(10)
net = Net()
result = net(input_layer)

print(result)


tensor([-0.2294, -0.2801,  0.0497, -0.4326], grad_fn=<AddBackward0>)


Your input will be images of size (28, 28), so images containing 784 pixels. Your network will contain an input_layer (provided for you), a hidden layer with 200units, and an output layer with 10 classes. The input layer has already been created for you. You are going to create the weights, and then do matrix multiplications, getting the results from the network.

Initialize with random numbers two matrices of weights, called weight_1 and weight_2.
Set the result of input_layer times weight_1 to hidden_1. Set the result of hidden_1 times weight_2 to output_layer.

In [ ]:
# Initialize the weights of the neural network
weight_1 = torch.rand(784, 200)
weight_2 = torch.rand(200, 10)

input_layer = torch.rand(784)
# Multiply input_layer with weight_1
hidden_1 = torch.matmul(input_layer, weight_1)

# Multiply hidden_1 with weight_2
output_layer = torch.matmul(hidden_1, weight_2)
print(output_layer)

tensor([19202.1328, 18568.8535, 18906.7637, 19783.7578, 19071.3594, 18778.5586,
        19076.8145, 17439.4980, 19487.7852, 19350.7754])


You are going to build the same neural network you built in the previous exercise, but now using the PyTorch way. As a reminder, you have 784 units in the input layer, 200 hidden units and 10 units for the output layer.

Instantiate two linear layers calling them self.fc1 and self.fc2. Determine their correct dimensions.
Implement the .forward() method, using the two layers you defined and returning x.

In [ ]:
class Net(nn.Module):
    def __init__(self):
        super(Net, self).__init__()
        
        # Instantiate all 2 linear layers  
        self.fc1 = nn.Linear(784, 200)
        self.fc2 = nn.Linear(200, 10)

    def forward(self, x):
      
        # Use the instantiated layers and return x
        x = self.fc1(x)
        x = self.fc2(x)
        return x

Activation functions

In [ ]:
import torch

input_layer = torch.tensor([2.,1.])
weight1 = torch.tensor([[0.45,0.32],[-0.12,0.29]])
h1 = torch.matmul(input_layer,weight1)
weight2 = torch.tensor([[0.48, -0.12],[0.64, 0.91]])
output_layer = torch.matmul(h1, weight2)
print(output_layer)

tensor([0.9696, 0.7527])


In [ ]:
weight = torch.matmul(weight1,weight2)
output = torch.matmul(input_layer, weight)
print(weight)
print(output)

tensor([[0.4208, 0.2372],
        [0.1280, 0.2783]])
tensor([0.9696, 0.7527])


In [ ]:
import torch.nn as nn

relu = nn.ReLU()

tensor = torch.tensor([2.,-4])

print(relu(tensor))

tensor([2., 0.])


In [ ]:
import torch.nn as nn 

relu = nn.ReLU()

tensor2 = torch.tensor([[2., -4.], [1.2, 0]])

print(relu(tensor2))

tensor([[2.0000, 0.0000],
        [1.2000, 0.0000]])



ReLU activation

In this exercise, we have the same settings as the previous exercise. But now we are going to build a neural network which has non-linearity. By doing so, we are going to convince ourselves that networks with multiple layers and non-linearity functions cannot be expressed as a neural network with one layer.

Apply the non-linearity to the two hidden layers and print the result.
Apply the non-linearity to the product of first two weights.
Multiply the result of the previous step with weight_3.
Multiply input_layer with weight and print the results

In [ ]:
input_layer = torch.rand(4)
weight_1 = torch.rand(4,4)
weight_2 = torch.rand(4,4)
weight_3 = torch.rand(4,4)

# Instantiate non-linearity
relu = nn.ReLU()

# Apply non-linearity on the hidden layers
hidden_1_activated = relu(torch.matmul(input_layer, weight_1))
hidden_2_activated = relu(torch.matmul(hidden_1_activated, weight_2))
print(torch.matmul(hidden_2_activated, weight_3))

# Apply non-linearity in the product of first two weights. 
weight_composed_1_activated = relu(torch.matmul(weight_1, weight_2))

# Multiply `weight_composed_1_activated` with `weight_3
weight = torch.matmul(weight_composed_1_activated, weight_3)

# Multiply input_layer with weight
print(torch.matmul(input_layer, weight))

tensor([4.5534, 5.8381, 5.5908, 3.4487])
tensor([4.5534, 5.8381, 5.5908, 3.4487])


Loss Functions

In [ ]:
logits = torch.tensor([[3.2,5.1,-1.7]])
ground_truth = torch.tensor([0])

#loss function 
criterion = nn.CrossEntropyLoss()

loss = criterion(logits, ground_truth)

print(loss)

tensor(2.0404)


In [ ]:
logits = torch.tensor([[10.2, 5.1, -1.7]])

loss = criterion(logits, ground_truth)

print(loss)


tensor(0.0061)


In [ ]:
logits = torch.tensor([[-10.2, 5.1, -1.7]])

loss = criterion(logits, ground_truth)

print(loss)

tensor(15.3011)


Initialize the tensor of scores with numbers [[-1.2, 0.12, 4.8]], and the tensor of ground truth [2].
Instantiate the cross-entropy loss and call it criterion.
Compute and print the loss.

In [ ]:
# Initialize the scores and ground truth
logits = torch.tensor([[-1.2, 0.12, 4.8]])
ground_truth = torch.tensor([2])

# Instantiate cross entropy loss
criterion = nn.CrossEntropyLoss()

# Compute and print the loss
loss = criterion(logits, ground_truth)
print(loss)

tensor(0.0117)


Loss function of random scores

If the neural network predicts random scores, what would be its loss function? Let's find it out in PyTorch. The neural network is going to have 1000 classes, each having a random score. For ground truth, it will have class 111. Calculate the loss function.

Import torch and torch.nn as nn
Initialize logits with a random tensor of shape (1, 1000) and ground_truth with a tensor containing the number 111.
Instantiate the cross-entropy loss in a variable called criterion.
Calculate and print the loss function.

In [ ]:
# Import torch and torch.nn
import torch
import torch.nn as nn

# Initialize logits and ground truth
logits = torch.rand(1,1000)
ground_truth = torch.tensor([111])

# Instantiate cross-entropy loss
criterion = nn.CrossEntropyLoss()

# Calculate and print the loss
loss = criterion(logits, ground_truth)
print(loss)

tensor(7.3550)


Data loaders

In [ ]:
import torch 
import torchvision
import torch.utils.data 
import torchvision.transforms as transforms

transform = transforms.Compose(
    [transforms.ToTensor(),
     transforms.Normalize((0.4914, 0.48216, 0.44543),
                          (0.24703, 0.24349, 0.26519))])



trainset = torchvision.datasets.CIFAR10(root="./data", train = True, download = True, transform = transform)
testset = torchvision.datasets.CIFAR10(root="./data", train = False, download = True, transform = transform)


trainloader = torch.utils.data.DataLoader(trainset, batch_size=32, shuffle = True, num_workers = 4)
testloader = torch.utils.data.DataLoader(testset, batch_size=32, shuffle = False, num_workers = 4)


Extracting ./data/cifar-10-python.tar.gz to ./data
Files already downloaded and verified


/usr/local/lib/python3.7/dist-packages/torch/utils/data/dataloader.py:477: UserWarning: This DataLoader will create 4 worker processes in total. Our suggested max number of worker in current system is 2, which is smaller than what this DataLoader is going to create. Please be aware that excessive worker creation might get DataLoader running slow or even freeze, lower the worker number to avoid potential slowness/freeze if necessary.
  cpuset_checked))


In [ ]:
#dataloader

print(testloader.dataset.data.shape)
print(trainloader.dataset.data.shape)

(10000, 32, 32, 3)
(50000, 32, 32, 3)


Preparing MNIST dataset

You are going to prepare dataloaders for MNIST training and testing set. As we explained in the lecture, MNIST has some differences to CIFAR-10, with the main difference being that MNIST images are grayscale (1 channel based) instead of RGB (3 channels).

Transform the data to torch tensors and normalize it to have mean is 0.1307 and std is 0.3081.
Prepare the trainset and the testset.
Prepare the dataloaders for training and testing so that only 32 pictures are processed at a time and the training data is shuffled each time.

In [ ]:
# Transform the data to torch tensors and normalize it 
transform = transforms.Compose([transforms.ToTensor(),
								transforms.Normalize((0.1307), ((0.3081)))])

# Prepare training set and testing set
trainset = torchvision.datasets.MNIST('mnist', train=True, 
									  download=True, transform=transform)
testset = torchvision.datasets.MNIST('mnist', train=False, 
									  download=True, transform=transform)

# Prepare training loader and testing loader
trainloader = torch.utils.data.DataLoader(trainset, batch_size=32,
										  shuffle=True, num_workers=0)
testloader = torch.utils.data.DataLoader(testset, batch_size=32,
										 shuffle=False, num_workers=0)       


Extracting mnist/MNIST/raw/train-images-idx3-ubyte.gz to mnist/MNIST/raw




Extracting mnist/MNIST/raw/train-labels-idx1-ubyte.gz to mnist/MNIST/raw




Extracting mnist/MNIST/raw/t10k-images-idx3-ubyte.gz to mnist/MNIST/raw




Extracting mnist/MNIST/raw/t10k-labels-idx1-ubyte.gz to mnist/MNIST/raw

Processing...
Done!


/usr/local/lib/python3.7/dist-packages/torchvision/datasets/mnist.py:502: UserWarning: The given NumPy array is not writeable, and PyTorch does not support non-writeable tensors. This means you can write to the underlying (supposedly non-writeable) NumPy array using the tensor. You may want to copy the array to protect its data or make it writeable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at  /pytorch/torch/csrc/utils/tensor_numpy.cpp:143.)
  return torch.from_numpy(parsed.astype(m[2], copy=False)).view(*s)


Inspecting the dataloaders

Now you are going to explore a bit the dataloaders you created in the previous exercise. In particular, you will compute the shape of the dataset in addition to the minibatch size.

Find the shapes of the trainset and testset.
Print the computed values.
Find the size of the minibatch for both trainset and testset.
Print the minibatch size.

In [ ]:
# Compute the shape of the training set and testing set
trainset_shape = trainloader.dataset.data.shape
testset_shape = testloader.dataset.data.shape

# Print the computed shapes
print(trainset_shape, testset_shape)

# Compute the size of the minibatch for training set and testing set
trainset_batchsize = trainloader.batch_size
testset_batchsize = testloader.batch_size

# Print sizes of the minibatch
print(trainset_batchsize, testset_batchsize)

torch.Size([60000, 28, 28]) torch.Size([10000, 28, 28])
32 32


Training a neural network

1.Data -> Dataloaders

2.Neural Network

  forward pass 
  loss calculation 
  gradients calculation
  update the weights

In [2]:
import torch
import torchvision
import torch.utils.data
import torchvision.transforms as transforms

transform = transforms.Compose(
    [transforms.ToTensor(),
     transforms.Normalize((0.4914, 0.48216, 0.44543),
                          (0.24703, 0.24349, 0.26519))])

trainset = torchvision.datasets.CIFAR10(root="./data", train = True, download = True, transform = transform)
testset = torchvision.datasets.CIFAR10(root="./data", train = False, download = True, transform = transform)


trainloader = torch.utils.data.DataLoader(trainset, batch_size=32, shuffle = True, num_workers = 4)
testloader = torch.utils.data.DataLoader(testset, batch_size=32, shuffle = False, num_workers = 4)


Extracting ./data/cifar-10-python.tar.gz to ./data
Files already downloaded and verified


/usr/local/lib/python3.7/dist-packages/torch/utils/data/dataloader.py:477: UserWarning: This DataLoader will create 4 worker processes in total. Our suggested max number of worker in current system is 2, which is smaller than what this DataLoader is going to create. Please be aware that excessive worker creation might get DataLoader running slow or even freeze, lower the worker number to avoid potential slowness/freeze if necessary.
  cpuset_checked))


In [3]:
import torch.nn.functional as F
import torch.nn as nn
import torch.optim as optim

class Net(nn.Module):
  def __init__(self):
    super(Net, self).__init__()
    self.fc1 = nn.Linear(32 * 32 * 3, 500)
    self.fc2 = nn.Linear(500,10)

  def forward(self, x):
    x = F.relu(self.fc1(x))
    return self.fc2(x)

In [ ]:
net = Net()

# loss function 
criterion = nn.CrossEntropyLoss()

# optimizer 
optimizer = optim.Adam(net.paramters(), lr = 1e-4)

for epoch in range(1):

  for i, data in enumerate