<a href="https://colab.research.google.com/github/RahulDogra-92/Deep-Learning-using-Pytorch/blob/main/Pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Matrix multiplication

In [59]:
import torch

#tensors
torch.tensor([[2,3,5],[1,2,9]])

tensor([[2, 3, 5],
        [1, 2, 9]])

In [60]:
#random values

torch.rand(2,2)

tensor([[0.6509, 0.1995],
        [0.2453, 0.3228]])

In [61]:
a = torch.rand((3,5))
print(a)
print(a.shape)

tensor([[0.8666, 0.4234, 0.5219, 0.1891, 0.3579],
        [0.5378, 0.2212, 0.0665, 0.7024, 0.3661],
        [0.3986, 0.7451, 0.0304, 0.3976, 0.5815]])
torch.Size([3, 5])


In [62]:
a = torch.rand((3,3))
b = torch.rand((3,3))

print(a,b)
# np.dot 
# torch.matmul

torch.matmul(a,b)

tensor([[0.5842, 0.0228, 0.9085],
        [0.1520, 0.4749, 0.7238],
        [0.1512, 0.7585, 0.0528]]) tensor([[0.8189, 0.1724, 0.7924],
        [0.7229, 0.3202, 0.0621],
        [0.1511, 0.7897, 0.9382]])


tensor([[0.6321, 0.8255, 1.3167],
        [0.5771, 0.7498, 0.8289],
        [0.6801, 0.3106, 0.2164]])

In [63]:
.85 * .86

0.731

In [64]:
a * b

tensor([[0.4784, 0.0039, 0.7199],
        [0.1098, 0.1521, 0.0449],
        [0.0228, 0.5990, 0.0495]])

In [65]:
torch.zeros(2,2)

tensor([[0., 0.],
        [0., 0.]])

In [66]:
torch.ones(2,2)

tensor([[1., 1.],
        [1., 1.]])

In [67]:
torch.eye(2)

tensor([[1., 0.],
        [0., 1.]])

In [68]:
x = torch .rand((3,5))
print(x)

tensor([[0.0473, 0.0988, 0.2322, 0.2192, 0.1276],
        [0.7643, 0.5673, 0.3603, 0.9009, 0.8476],
        [0.4299, 0.4324, 0.6485, 0.8227, 0.4236]])


In [69]:
torch.from_numpy(x.numpy())

tensor([[0.0473, 0.0988, 0.2322, 0.2192, 0.1276],
        [0.7643, 0.5673, 0.3603, 0.9009, 0.8476],
        [0.4299, 0.4324, 0.6485, 0.8227, 0.4236]])

In [70]:
l = [1,2,3,4]
torch.tensor(l)

tensor([1, 2, 3, 4])

**Practise**

Import PyTorch main library.
Create the variable your_first_tensor and set it to a random torch tensor of size 3 by 3.
Calculate its shape (dimension sizes) and set it to variable tensor_size.
Print the values of your_first_tensor and tensor_size

In [71]:
import torch

your_first_tensor = torch.tensor((3, 3))

tensor_size = your_first_tensor.shape

print(your_first_tensor)
print(tensor_size)


tensor([3, 3])
torch.Size([2])


Create a matrix of ones with shape 3 by 3, and put it on variable tensor_of_ones.
Create an identity matrix with shape 3 by 3, and put it on variable identity_tensor.
Do a matrix multiplication of tensor_of_ones with identity_tensor and print its value.
Do an element-wise multiplication of tensor_of_ones with identity_tensor and print its value.

In [72]:

# Create a matrix of ones with shape 3 by 3
tensor_of_ones = torch.ones(3, 3)

# Create an identity matrix with shape 3 by 3
identity_tensor = torch.eye(3)

# Do a matrix multiplication of tensor_of_ones with identity_tensor
matrices_multiplied = torch.matmul(tensor_of_ones, identity_tensor)
print(matrices_multiplied)

# Do an element-wise multiplication of tensor_of_ones with identity_tensor
element_multiplication = tensor_of_ones * identity_tensor
print(element_multiplication)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])
tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])


Forward Pass

In [73]:
import torch

a = torch.tensor([2])
b = torch.tensor([-4])
c = torch.tensor([-2])
d = torch.tensor([2])

e = a + b
f = c * d

g = e * f

print(e,f,g)

tensor([-2]) tensor([-4]) tensor([8])


Initialize random tensors x, y and z, each having shape (1000, 1000).
Multiply x with y, putting the result in tensor q.
Do an elementwise multiplication of tensor z with tensor q, putting the results in f

In [74]:
# Initialize tensors x, y and z
x = torch.rand(1000, 1000)
y = torch.rand(1000, 1000)
z = torch.rand(1000, 1000)

# Multiply x with y
q = x * y

# Multiply elementwise z with q
f = z * q

mean_f = torch.mean(f)
print(mean_f)

tensor(0.1250)


BackProp by auto diff

In [75]:
import torch

x = torch.tensor(-3.,requires_grad=True)
y = torch.tensor(-5.,requires_grad=True)
z = torch.tensor(2.,requires_grad=True)

q = x + y
f = q * z

f.backward()

print("gradient of z", str(z.grad))
print("gradient of y", str(y.grad))
print("gradient of x", str(x.grad))

gradient of z tensor(-8.)
gradient of y tensor(2.)
gradient of x tensor(2.)


Initialize tensors x, y and z to values 4, -3 and 5.
Put the sum of tensors x and y in q, put the product of q and z in f.
Calculate the derivatives of the computational graph.
Print the gradients of the x, y and z tensors.

In [76]:
# Initialize x, y and z to values 4, -3 and 5
x = torch.tensor(4., requires_grad=True)
y = torch.tensor(-3., requires_grad=True)
z = torch.tensor(5., requires_grad=True)

# Set q to sum of x and y, set f to product of q with z
q = x + y
f = q * z

# Compute the derivatives
f.backward()

# Print the gradients
print("Gradient of x is: " + str(x.grad))
print("Gradient of y is: " + str(y.grad))
print("Gradient of z is: " + str(z.grad))

Gradient of x is: tensor(5.)
Gradient of y is: tensor(5.)
Gradient of z is: tensor(1.)


Multiply tensors x and y, put the product in tensor q.
Do an elementwise multiplication of tensors z with q.
Calculate the gradients.

In [77]:
x = torch.randn(1000,1000,requires_grad=True)
y = torch.randn(1000,1000,requires_grad=True)
z = torch.randn(1000,1000,requires_grad=True)
# Multiply tensors x and y
q = torch.matmul(x,y)

# Elementwise multiply tensors z with q
f = z * q

mean_f = torch.mean(f)

# Calculate the gradients
mean_f.backward()

Intro to Neural Networks

In [78]:
#Work of Hidden Layers is to get good features

import torch

input_layer = torch.rand(10)

w1 = torch.rand(10,20)
w2 = torch.rand(20,20)
w3 = torch.rand(20,4)

h1 = torch.matmul(input_layer , w1)
h2 = torch.matmul(h1,w2)

output_layer = torch.matmul(h2, w3)

print(output_layer)

tensor([286.3852, 285.6194, 253.3238, 268.5671])


Pytorch way

In [79]:
import torch
import torch.nn as nn

class Net(nn.Module):
  def __init__(self):
    super(Net, self).__init__() #calling the super class constructor
    self.fc1 = nn.Linear(10,20)
    self.fc2 = nn.Linear(20,20)
    self.output = nn.Linear(20,4)

  def forward(self, X):
    x1 = self.fc1(X)
    x2 = self.fc2(x1)
    x3 = self.output(x2)
    return x3

input_layer = torch.rand(10)
net = Net()
result = net(input_layer)

print(result)


tensor([-0.1931, -0.5404,  0.1651,  0.0773], grad_fn=<AddBackward0>)


Your input will be images of size (28, 28), so images containing 784 pixels. Your network will contain an input_layer (provided for you), a hidden layer with 200units, and an output layer with 10 classes. The input layer has already been created for you. You are going to create the weights, and then do matrix multiplications, getting the results from the network.

Initialize with random numbers two matrices of weights, called weight_1 and weight_2.
Set the result of input_layer times weight_1 to hidden_1. Set the result of hidden_1 times weight_2 to output_layer.

In [80]:
# Initialize the weights of the neural network
weight_1 = torch.rand(784, 200)
weight_2 = torch.rand(200, 10)

input_layer = torch.rand(784)
# Multiply input_layer with weight_1
hidden_1 = torch.matmul(input_layer, weight_1)

# Multiply hidden_1 with weight_2
output_layer = torch.matmul(hidden_1, weight_2)
print(output_layer)

tensor([19340.6582, 18789.8867, 19137.4785, 20068.4375, 19785.4258, 19170.7480,
        19271.6602, 19477.5059, 19239.8105, 18699.7090])


You are going to build the same neural network you built in the previous exercise, but now using the PyTorch way. As a reminder, you have 784 units in the input layer, 200 hidden units and 10 units for the output layer.

Instantiate two linear layers calling them self.fc1 and self.fc2. Determine their correct dimensions.
Implement the .forward() method, using the two layers you defined and returning x.

In [81]:
class Net(nn.Module):
    def __init__(self):
        super(Net, self).__init__()
        
        # Instantiate all 2 linear layers  
        self.fc1 = nn.Linear(784, 200)
        self.fc2 = nn.Linear(200, 10)

    def forward(self, x):
      
        # Use the instantiated layers and return x
        x = self.fc1(x)
        x = self.fc2(x)
        return x

Activation functions

In [82]:
import torch

input_layer = torch.tensor([2.,1.])
weight1 = torch.tensor([[0.45,0.32],[-0.12,0.29]])
h1 = torch.matmul(input_layer,weight1)
weight2 = torch.tensor([[0.48, -0.12],[0.64, 0.91]])
output_layer = torch.matmul(h1, weight2)
print(output_layer)

tensor([0.9696, 0.7527])


In [83]:
weight = torch.matmul(weight1,weight2)
output = torch.matmul(input_layer, weight)
print(weight)
print(output)

tensor([[0.4208, 0.2372],
        [0.1280, 0.2783]])
tensor([0.9696, 0.7527])


In [84]:
import torch.nn as nn

relu = nn.ReLU()

tensor = torch.tensor([2.,-4])

print(relu(tensor))

tensor([2., 0.])


In [85]:
import torch.nn as nn 

relu = nn.ReLU()

tensor2 = torch.tensor([[2., -4.], [1.2, 0]])

print(relu(tensor2))

tensor([[2.0000, 0.0000],
        [1.2000, 0.0000]])



ReLU activation

In this exercise, we have the same settings as the previous exercise. But now we are going to build a neural network which has non-linearity. By doing so, we are going to convince ourselves that networks with multiple layers and non-linearity functions cannot be expressed as a neural network with one layer.

Apply the non-linearity to the two hidden layers and print the result.
Apply the non-linearity to the product of first two weights.
Multiply the result of the previous step with weight_3.
Multiply input_layer with weight and print the results

In [86]:
input_layer = torch.rand(4)
weight_1 = torch.rand(4,4)
weight_2 = torch.rand(4,4)
weight_3 = torch.rand(4,4)

# Instantiate non-linearity
relu = nn.ReLU()

# Apply non-linearity on the hidden layers
hidden_1_activated = relu(torch.matmul(input_layer, weight_1))
hidden_2_activated = relu(torch.matmul(hidden_1_activated, weight_2))
print(torch.matmul(hidden_2_activated, weight_3))

# Apply non-linearity in the product of first two weights. 
weight_composed_1_activated = relu(torch.matmul(weight_1, weight_2))

# Multiply `weight_composed_1_activated` with `weight_3
weight = torch.matmul(weight_composed_1_activated, weight_3)

# Multiply input_layer with weight
print(torch.matmul(input_layer, weight))

tensor([3.1341, 4.7171, 2.6683, 3.0647])
tensor([3.1341, 4.7171, 2.6683, 3.0647])


Loss Functions

In [87]:
logits = torch.tensor([[3.2,5.1,-1.7]])
ground_truth = torch.tensor([0])

#loss function 
criterion = nn.CrossEntropyLoss()

loss = criterion(logits, ground_truth)

print(loss)

tensor(2.0404)


In [88]:
logits = torch.tensor([[10.2, 5.1, -1.7]])

loss = criterion(logits, ground_truth)

print(loss)


tensor(0.0061)


In [89]:
logits = torch.tensor([[-10.2, 5.1, -1.7]])

loss = criterion(logits, ground_truth)

print(loss)

tensor(15.3011)


Initialize the tensor of scores with numbers [[-1.2, 0.12, 4.8]], and the tensor of ground truth [2].
Instantiate the cross-entropy loss and call it criterion.
Compute and print the loss.

In [90]:
# Initialize the scores and ground truth
logits = torch.tensor([[-1.2, 0.12, 4.8]])
ground_truth = torch.tensor([2])

# Instantiate cross entropy loss
criterion = nn.CrossEntropyLoss()

# Compute and print the loss
loss = criterion(logits, ground_truth)
print(loss)

tensor(0.0117)


Loss function of random scores

If the neural network predicts random scores, what would be its loss function? Let's find it out in PyTorch. The neural network is going to have 1000 classes, each having a random score. For ground truth, it will have class 111. Calculate the loss function.

Import torch and torch.nn as nn
Initialize logits with a random tensor of shape (1, 1000) and ground_truth with a tensor containing the number 111.
Instantiate the cross-entropy loss in a variable called criterion.
Calculate and print the loss function.

In [91]:
# Import torch and torch.nn
import torch
import torch.nn as nn

# Initialize logits and ground truth
logits = torch.rand(1,1000)
ground_truth = torch.tensor([111])

# Instantiate cross-entropy loss
criterion = nn.CrossEntropyLoss()

# Calculate and print the loss
loss = criterion(logits, ground_truth)
print(loss)

tensor(7.0851)


Data loaders

In [92]:
import torch 
import torchvision
import torch.utils.data 
import torchvision.transforms as transforms

transform = transforms.Compose(
    [transforms.ToTensor(),
     transforms.Normalize((0.4914, 0.48216, 0.44543),
                          (0.24703, 0.24349, 0.26519))])



trainset = torchvision.datasets.CIFAR10(root="./data", train = True, download = True, transform = transform)
testset = torchvision.datasets.CIFAR10(root="./data", train = False, download = True, transform = transform)


trainloader = torch.utils.data.DataLoader(trainset, batch_size=32, shuffle = True, num_workers = 4)
testloader = torch.utils.data.DataLoader(testset, batch_size=32, shuffle = False, num_workers = 4)

Files already downloaded and verified
Files already downloaded and verified


/usr/local/lib/python3.7/dist-packages/torch/utils/data/dataloader.py:477: UserWarning: This DataLoader will create 4 worker processes in total. Our suggested max number of worker in current system is 2, which is smaller than what this DataLoader is going to create. Please be aware that excessive worker creation might get DataLoader running slow or even freeze, lower the worker number to avoid potential slowness/freeze if necessary.
  cpuset_checked))


In [93]:
#dataloader

print(testloader.dataset.data.shape)
print(trainloader.dataset.data.shape)

(10000, 32, 32, 3)
(50000, 32, 32, 3)


Preparing MNIST dataset

You are going to prepare dataloaders for MNIST training and testing set. As we explained in the lecture, MNIST has some differences to CIFAR-10, with the main difference being that MNIST images are grayscale (1 channel based) instead of RGB (3 channels).

Transform the data to torch tensors and normalize it to have mean is 0.1307 and std is 0.3081.
Prepare the trainset and the testset.
Prepare the dataloaders for training and testing so that only 32 pictures are processed at a time and the training data is shuffled each time.

In [94]:
# Transform the data to torch tensors and normalize it 
transform = transforms.Compose([transforms.ToTensor(),
								transforms.Normalize((0.1307), ((0.3081)))])

# Prepare training set and testing set
trainset = torchvision.datasets.MNIST('mnist', train=True, 
									  download=True, transform=transform)
testset = torchvision.datasets.MNIST('mnist', train=False, 
									  download=True, transform=transform)

# Prepare training loader and testing loader
trainloader = torch.utils.data.DataLoader(trainset, batch_size=32,
										  shuffle=True, num_workers=0)
testloader = torch.utils.data.DataLoader(testset, batch_size=32,
										 shuffle=False, num_workers=0)       

Inspecting the dataloaders

Now you are going to explore a bit the dataloaders you created in the previous exercise. In particular, you will compute the shape of the dataset in addition to the minibatch size.

Find the shapes of the trainset and testset.
Print the computed values.
Find the size of the minibatch for both trainset and testset.
Print the minibatch size.

In [95]:
# Compute the shape of the training set and testing set
trainset_shape = trainloader.dataset.data.shape
testset_shape = testloader.dataset.data.shape

# Print the computed shapes
print(trainset_shape, testset_shape)

# Compute the size of the minibatch for training set and testing set
trainset_batchsize = trainloader.batch_size
testset_batchsize = testloader.batch_size

# Print sizes of the minibatch
print(trainset_batchsize, testset_batchsize)

torch.Size([60000, 28, 28]) torch.Size([10000, 28, 28])
32 32


Training a neural network

1.Data -> Dataloaders

2.Neural Network

  forward pass 
  loss calculation 
  gradients calculation
  update the weights

In [96]:
import torch
import torchvision
import torch.utils.data
import torchvision.transforms as transforms

transform = transforms.Compose(
    [transforms.ToTensor(),
     transforms.Normalize((0.4914, 0.48216, 0.44543),
                          (0.24703, 0.24349, 0.26519))])

trainset = torchvision.datasets.CIFAR10(root="./data", train = True, download = True, transform = transform)
testset = torchvision.datasets.CIFAR10(root="./data", train = False, download = True, transform = transform)


trainloader = torch.utils.data.DataLoader(trainset, batch_size=32, shuffle = True, num_workers = 4)
testloader = torch.utils.data.DataLoader(testset, batch_size=32, shuffle = False, num_workers = 4)

Files already downloaded and verified
Files already downloaded and verified


/usr/local/lib/python3.7/dist-packages/torch/utils/data/dataloader.py:477: UserWarning: This DataLoader will create 4 worker processes in total. Our suggested max number of worker in current system is 2, which is smaller than what this DataLoader is going to create. Please be aware that excessive worker creation might get DataLoader running slow or even freeze, lower the worker number to avoid potential slowness/freeze if necessary.
  cpuset_checked))


In [97]:
import torch.nn.functional as F
import torch.nn as nn
import torch.optim as optim

class Net(nn.Module):
  def __init__(self):
    super(Net, self).__init__()
    self.fc1 = nn.Linear(32 * 32 * 3, 500)
    self.fc2 = nn.Linear(500,10)

  def forward(self, x):
    x = F.relu(self.fc1(x))
    return self.fc2(x)

In [98]:
net = Net()

# loss function 
criterion = nn.CrossEntropyLoss()

# optimizer 
optimizer = optim.Adam(net.parameters(), lr = 1e-4)


for epoch in range(1):

  for i, data in enumerate(trainloader):
      inputs, labels = data 

      # total number of features = 32x32x3
      inputs = inputs.view(-1, 32*32*3)
      
      # zero the parameter gradients 
      optimizer.zero_grad()

      # forward + backward + optimization 

      outputs = net(inputs)
      loss = criterion(outputs, labels)
      loss.backward()

      # update the weights 
      optimizer.step()

/usr/local/lib/python3.7/dist-packages/torch/utils/data/dataloader.py:477: UserWarning: This DataLoader will create 4 worker processes in total. Our suggested max number of worker in current system is 2, which is smaller than what this DataLoader is going to create. Please be aware that excessive worker creation might get DataLoader running slow or even freeze, lower the worker number to avoid potential slowness/freeze if necessary.
  cpuset_checked))


In [99]:
predictions = []
correct = 0
total = 0 

# we tell that we are going to evaluate now 
net.eval()

for i, data in enumerate(testloader):
  inputs, labels = data 
  inputs = inputs.view(-1, 32*32*3)

  outputs = net(inputs)

  _, predicted = torch.max(outputs, 1)
  predictions.append(outputs)

  # probs = torch.nn.functional.softmax(outputs)

  # print(probs)

  # sum value 

  # total = torch.sum(probs, 1)
  # print(total)
  total += labels.size(0) # give me the first value of the shape -> 32x1 
  correct += (predicted == labels).sum().item()
  

print("The testing accuracy si %d %%" % (100 * correct / total))

/usr/local/lib/python3.7/dist-packages/torch/utils/data/dataloader.py:477: UserWarning: This DataLoader will create 4 worker processes in total. Our suggested max number of worker in current system is 2, which is smaller than what this DataLoader is going to create. Please be aware that excessive worker creation might get DataLoader running slow or even freeze, lower the worker number to avoid potential slowness/freeze if necessary.
  cpuset_checked))


The testing accuracy si 46 %



=======================================
Build a class for a neural network which will be used to train on the MNIST dataset. The dataset contains images of shape (28, 28, 1), so you should deduct the size of the input layer. For hidden layer use 200 units, while for output layer use 10 units (1 for each class). For activation function, use relu in a functional way (nn.Functional is already imported as F).

For context, the same net will be trained and used to make predictions in the next two exercises.

Define the class called Net which inherits from nn.Module.
In the __init__() method, define the parameters for the two fully connected layers.
In the .forward() method, do the forward step.

In [100]:
# Define the class Net
class Net(nn.Module):
    def __init__(self):    
    	# Define all the parameters of the net
        super(Net, self).__init__()
        self.fc1 = nn.Linear(28 * 28 * 1, 200)
        self.fc2 = nn.Linear(200, 10)

    def forward(self, x):    
    	# Do the forward pass
        x = F.relu(self.fc1(x))
        x = self.fc2(x)
        return x


Given the fully connected neural network (called model) which you built in the previous exercise and a train loader called train_loader containing the MNIST dataset (which we created for you), you're to train the net in order to predict the classes of digits. You will use the Adam optimizer to optimize the network, and considering that this is a classification problem you are going to use cross entropy as loss function.

Instantiate the Adam optimizer with learning rate 3e-4 and instantiate Cross-Entropy as loss function.
Complete a forward pass on the neural network using the input data.
Using backpropagation, compute the gradients of the weights, and then change the weights using the Adam optimizer.

In [101]:
#do not change code
# Transform the data to torch tensors and normalize it 
transform = transforms.Compose([transforms.ToTensor(),
								transforms.Normalize((0.1307), ((0.3081)))])

# Prepare training set and testing set
trainset = torchvision.datasets.MNIST('mnist', train=True, 
									  download=True, transform=transform)
testset = torchvision.datasets.MNIST('mnist', train=False, 
									  download=True, transform=transform)

# Prepare training loader and testing loader
train_loader = torch.utils.data.DataLoader(trainset, batch_size=32,
										  shuffle=True, num_workers=0)
test_loader = torch.utils.data.DataLoader(testset, batch_size=32,
										 shuffle=False, num_workers=0)  

In [102]:
# Instantiate the network, the Adam optimizer and Cross-Entropy loss function
model = Net()   
optimizer = optim.Adam(model.parameters(), lr=3e-4)
criterion = nn.CrossEntropyLoss()

for batch_idx, data_target in enumerate(train_loader):
    data = data_target[0]
    target = data_target[1]
    data = data.view(-1, 28 * 28)
    optimizer.zero_grad()

    # Complete a forward pass
    output = model(data)

    # Compute the loss, gradients and change the weights
    loss = criterion(output, target)
    loss.backward()
    optimizer.step()

Using the network to make predictions

Now that you have trained the network, use it to make predictions for the data in the testing set. The network is called model (same as in the previous exercise), and the loader is called test_loader. We have already initialized variables total and correct to 0.

Set the network in testing (eval) mode.
Put each image into a vector using inputs.view(-1, number_of_features) where the number of features should be deducted by multiplying spatial dimensions (shape) of the image.
Do the forward pass and put the predictions in output variable.

In [103]:
# Set the model in eval mode
model.eval()

for i, data in enumerate(test_loader, 0):
    inputs, labels = data
    
    # Put each image into a vector
    inputs = inputs.view(-1, 28 * 28)
    
    # Do the forward pass and get the predictions
    outputs = model(inputs)
    _, outputs = torch.max(outputs.data, 1)
    total += labels.size(0)
    correct += (outputs == labels).sum().item()
print('The testing set accuracy of the network is: %d %%' % (100 * correct / total))

The testing set accuracy of the network is: 71 %
